/**
 * Base request structure used by the WAF.
 * Framework adapters (Express, Hono, Nest...) must convert
 * their native request into this format.
 */
export interface WafRequest {
  ip: string;
  method: string;
  url: string;
  headers: Record<string, string>;
  body?: unknown;
}

/**
 * Response generated by the WAF.
 * Middlewares will translate this into framework-specific responses.
 */
export interface WafResponse {
  status: number;
  message: string;
}

/**
 * A single detection result produced by a detector.
 */
export interface WafFinding {
  detector: string;
  severity: number; // 1–10
  message: string;
  metadata?: Record<string, unknown>;
}

/**
 * Final decision returned by the WAF pipeline.
 */
export interface WafDecision {
  action: "allow" | "block";
  score: number;
  findings: WafFinding[];
}

/**
 * Provider interface (GeoIP, ASN, DNS, RateLimit…)
 */
export interface WafProvider {
  name: string;
  init(): Promise<void>;
}

/**
 * Detector interface (SQLi, XSS, LFI, UA…)
 */
export interface WafDetector {
  name: string;
  run(ctx: WafContext): Promise<WafFinding[]>;
}

/**
 * Context shared across the entire pipeline.
 * (Declared here to avoid circular imports)
 */
export interface WafContext {
  request: WafRequest;
  response: WafResponse | null;
  findings: WafFinding[];
  metadata: Record<string, unknown>;
  providers: Map<string, WafProvider>;
}

/**
 * Optional: middleware adapter interface
 * (Express, Hono, Nest, Node)
 */
export interface WafMiddlewareAdapter {
  name: string;
  handle(req: unknown, res: unknown, next?: unknown): Promise<void>;
}
